"""Changed 'caption' to 'text' in post model

Revision ID: a4ad656b8fb1
Revises: f4a9c315fa06
Create Date: 2022-12-15 03:56:28.160624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ad656b8fb1'
down_revision = 'f4a9c315fa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=500), nullable=True))
        batch_op.drop_column('caption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
