"""Added following/followed count to user model

Revision ID: e98b3fedbc4d
Revises: a6a0f8803a23
Create Date: 2022-12-15 01:48:29.578627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98b3fedbc4d'
down_revision = 'a6a0f8803a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('no_of_followed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('no_of_followed')
        batch_op.drop_column('no_of_followers')

    # ### end Alembic commands ###
